services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    ports:
      - "5002:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${STACKS_DIR}:/stacks
      - ${DATA_DIR}:/dockhand
    environment:
      - DATA_DIR=/dockhand

volumes:
  dockhand_data:
