name: monitor-stack
services:
  glance:
    image: glanceapp/glance
    container_name: glance
    volumes:
      - ./glance/config:/app/config
      - ./glance/assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /JaanNAS:/JaanNAS:ro
    ports:
      - 80:8080
    restart: unless-stopped

  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket
    environment:
      USER_CREATION: true
      DISABLE_PASSWORD_AUTH: true

  beszel-agent:
    image: henrygd/beszel-agent-intel:latest
    container_name: beszel-agent
    network_mode: host
    cap_add:
      - CAP_PERFMON
      - SYS_RAWIO
    volumes:
      - ./beszel_agent_data:/var/lib/beszel-agent
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /JaanNAS:/extra-filesystems/mergerfs__JaanNAS:ro
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/disk/by-id/ata-WDC_WD40EFRX-68N32N0_WD-WCC7K5SZATLK:/dev/disk/by-id/ata-WDC_WD40EFRX-68N32N0_WD-WCC7K5SZATLK
      - /dev/disk/by-id/ata-WDC_WD40EFRX-68N32N0_WD-WCC7K6TP8Y8S:/dev/disk/by-id/ata-WDC_WD40EFRX-68N32N0_WD-WCC7K6TP8Y8S
      - /dev/disk/by-id/ata-WDC_WD40EFRX-68WT0N0_WD-WCC4E0050794:/dev/disk/by-id/ata-WDC_WD40EFRX-68WT0N0_WD-WCC4E0050794
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: http://192.168.1.10:8090
      TOKEN: ${BESZEL_TOKEN}
      KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJvzMOmFpIHbBModwWV53dKGGEdffNSWsc3ncwswcY8N"
    restart: unless-stopped

  healthchecks:
    image: lscr.io/linuxserver/healthchecks:latest
    container_name: healthchecks
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - SITE_ROOT=http://192.168.1.10:8001
      - SITE_NAME=Bakske Healthchecks
      - SUPERUSER_EMAIL=${HC_SUPERUSER_EMAIL}
      - SUPERUSER_PASSWORD=${HC_SUPERUSER_PASSWORD}
      - SECRET_KEY=${HC_SECRET_KEY}
    volumes:
      - ./healthchecks/config:/config
    ports:
      - 8001:8000
    restart: unless-stopped
