services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - HARDCOVER_TOKEN=${HARDCOVER_TOKEN}
      - NETWORK_SHARE_MODE=false
      - CWA_PORT_OVERRIDE=8083
    volumes:
      - ./calibre-web-automated/config:/config
      - ./media/ingest:/cwa-book-ingest
      - ./media/books:/calibre-library
      - ./calibre-web-automated/plugins:/config/.config/calibre/plugins
    ports:
      - 8083:8083
    restart: unless-stopped

  shelfmark:
    image: ghcr.io/calibrain/shelfmark:latest
    container_name: shelfmark
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    ports:
      - 8084:8084
    restart: unless-stopped
    volumes:
      - ./media/ingest:/books
      - /path/to/config:/config

networks: {}